#!/usr/bin/python3

# pihsm: Turn your Raspberry Pi into a Hardware Security Module 
# Copyright (C) 2017 System76, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import sys

import pihsm
from pihsm.common import compute_digest, b32enc, log_response
from pihsm.ipc import ClientClient


log = pihsm.configure_logging(__name__)

# We'll likely add options eventually:
parser = argparse.ArgumentParser()
args = parser.parse_args()

# We need stdin, stdout opened in binary mode:
manifest = sys.stdin.buffer.read()
digest = compute_digest(manifest)
log.info('--> Manifest: %s (%d bytes)', b32enc(digest), len(manifest))

client = ClientClient()
response = client.make_request(digest)
assert len(response) == 400
sys.stdout.buffer.write(response)
sys.stdout.buffer.flush()

log_response(response)

