#!/usr/bin/python3

# pihsm: Turn your Raspberry Pi into a Hardware Security Module 
# Copyright (C) 2017 System76, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import time
import os

import smbus

import pihsm
from pihsm.display import LCD, Manager
from pihsm.sign import Signer, get_time


log = pihsm.configure_logging(__name__)


bus = smbus.SMBus(1)
lcd = LCD(bus)
manager = Manager(lcd)
manager.start_worker_thread()

time.sleep(30)
s = Signer()
manager.update_screens(s.genesis)

c = Signer()
while True:
    time.sleep(30)
    request = c.sign(get_time(), os.urandom(48))
    response = s.sign(get_time(), request)
    manager.update_screens(response)

