#!/usr/bin/python3

# pihsm: Turn your Raspberry Pi into a Hardware Security Module 
# Copyright (C) 2017 System76, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import pihsm
from pihsm.sign import Signer
from pihsm.ipc import open_activated_socket, PrivateServer, DisplayClient

log = pihsm.configure_logging(__name__)


# Create private key, send genesis signature to display server:
display_client = DisplayClient('/run/pihsm/display.socket')
signer = Signer()
display_client.make_request(signer.genesis)

# Open systemd activated AF_UNIX socket, setup IPC server:
sock = open_activated_socket()
server = PrivateServer(sock, display_client, signer)

# Start server:
server.serve_forever()

