#!/usr/bin/python3

# pihsm: Turn your Raspberry Pi into a Hardware Security Module 
# Copyright (C) 2017 System76, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import serial
import os
import time

import pihsm
from pihsm.common import b32enc, get_signature, get_counter
from pihsm.sign import Signer
from pihsm.serial import open_serial, read_serial


log = pihsm.configure_logging(__name__)


ttl = open_serial('/dev/ttyUSB0', serial.Serial)
s = Signer()
for i in range(100):
    request = s.sign(os.urandom(48))
    ttl.write(request)
    response = read_serial(ttl, 400)
    print(get_counter(response), b32enc(get_signature(response)))
    time.sleep(1)

