#!/usr/bin/python3

# pihsm: Turn your Raspberry Pi into a Hardware Security Module 
# Copyright (C) 2017 System76, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import pihsm
from pihsm.common import load_display_config
from pihsm.display import LCD, DisplayLoop


config = load_display_config()
log = pihsm.configure_logging(__name__, debug=config['debug'])


if config['use_hardware'] is True:
    import smbus
    bus = smbus.SMBus(config['i2c_bus'])
else:
    class MockBus:
        def write_byte(self, addr, bits):
            pass
    bus = MockBus()
    log.warning('Not enabling I2C display interaction')

lcd = LCD(bus, config['lcd_i2c_address'], debug=config['debug'])
display_loop = DisplayLoop(lcd)
display_loop.run_forever()

