#!/usr/bin/python3

# pihsm: Turn your Raspberry Pi into a Hardware Security Module 
# Copyright (C) 2017 System76, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import os
from os import path
import time

import pihsm
from pihsm.common import compute_digest, log_response
from pihsm.ipc import ClientClient


log = pihsm.configure_logging(__name__)


parser = argparse.ArgumentParser()
parser.add_argument('filename',
    help='Path to manifest file to sign'
)
args = parser.parse_args()
filename = path.abspath(args.filename)

with open(filename, 'rb', 0) as fp:
    content = fp.read()
digest = compute_digest(content)
    
client = ClientClient()
for i in range(100):
    response = client.make_request(os.urandom(48))
    log_response(response)
    time.sleep(1)
